# Generated by terraform-provider-packernix
# Should mostly match <nixpkgs/nixos/lib/eval-config.nix>

{ nixpkgs ? (import {{.Nixpkgs}} {})
, mod ? (import {{.File}})
, modulesPath ? "{{.Nixpkgs}}/nixos/modules"
, baseModules ? (import ({{.Nixpkgs}} + /nixos/modules/module-list.nix))
, tfpnModulesPath ? "{{.TfpnModPath}}"
}:
let
  inherit (nixpkgs) lib;
  tfpnmod = { config, lib, ... }: {
    options.tfpn = lib.mkOption {
      description = "Option passed from terraform-provider-packernix";
    };
    config.tfpn = builtins.fromJSON (builtins.readFile ./tfpn-config.json);
  };
  pkgsModule = rec {
    config = {
      nixpkgs = {
        system = lib.mkDefault builtins.currentSystem;
        initialSystem = builtins.currentSystem;
      };
    };
  };
in
let
  c = lib.evalModules {
    modules = [
      tfpnmod
      pkgsModule
      mod
    ];
    specialArgs = {
      inherit modulesPath baseModules tfpnModulesPath;
    };
  };
in
  c.config.system.build.toplevel
